#!/usr/bin/python

import time
import argparse
import openpd

parser = argparse.ArgumentParser()
parser.add_argument('-t', '--timestamps', action='store_true', help='Emit timestamps with samples')
parser.add_argument('-n', '--period', type=float, default=0.5, help='Sampling period in seconds')
parser.add_argument('-d', '--device', type=argparse.FileType('r'), help='Sampling period in seconds')
args = parser.parse_args()

meter  = openpd.PowerMeter(args.device)
while True:
    _, power = meter.sample()
    if args.timestamps:
        log.write('%f\t%g\n' % (time.time(), power))
    else:
        log.write('%g\n' % power)

    log.flush()
    time.sleep(args.period)
