#!/usr/bin/env python

import argparse
import openpd
import zmq

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--device', required=True,
                    type=argparse.FileType('r'), help='Device path')
args = parser.parse_args()

device = '/dev/ttyUSB.openpd'
if args.device is not None:
    device = args.device.name
dev = openpd.RawOpenPD(device)

ctx = zmq.Context()
s = ctx.socket(zmq.REP)
s.bind(openpd._device_socket(device))
while True:
    s.recv()
    s.send('%d %g' % dev.sample())
