#!/usr/bin/env python

import argparse
import os
import openpd
import zmq

def main(device):
    dev = openpd.RawOpenPD(device)
    daemon = openpd.Daemon()
    daemon.add_device(dev)
    daemon.run()

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--device', type=argparse.FileType('r'), help='Device path')
parser.add_argument('-f', '--fork', action='store_true', help='Run as daemon')
args = parser.parse_args()

device = '/dev/ttyUSB.openpd'
if args.device is not None:
    device = args.device.name
if args.fork:
    import daemon
    with daemon.DaemonContext():
        main(device)
else:
    main(device)
