#!/usr/bin/env python

import argparse
import os
import openpd
import zmq

def main(devices):
    daemon = openpd.Daemon()
    for dev in devices:
        dev = openpd.RawOpenPD(dev)
        daemon.add_device(dev)
    daemon.run()

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--device', type=str, default=[], action='append',
                    metavar='PORT', help='Device path')
parser.add_argument('-f', '--fork', action='store_true', help='Run as daemon')
args = parser.parse_args()

if args.fork:
    import daemon
    with daemon.DaemonContext():
        main(args.device)
else:
    main(args.device)
