#!/usr/bin/env python

from __future__ import print_function
import time
import argparse
import openpd
import sys

def open_device(args):
    if args.raw:
        if args.device is None:
            raise RuntimeError('Must specify device path when running with --raw')
        else:
            return openpd.RawOpenPD(args.device)
    else:
        conn = openpd.Connection()
        if args.device is None:
            devices = conn.list_devices()
            if len(devices) == 0:
                raise RuntimeError('Daemon knows of no devices')
            return conn.device(devices[0])
        else:
            return conn.device(args.device)

def acquire(args):
    meter = open_device(args)
    output = args.output
    while True:
        power = meter.sample()['power']
        if args.timestamps:
            output.write('%f\t%g\n' % (time.time(), power))
        else:
            output.write('%g\n' % power)

        output.flush()
        time.sleep(args.period)

def configure(args):
    meter = open_device(args)
    if args.wavelength is not None:
        meter.set_wavelength(args.wavelength)
    print('wavelength = %d' % int(meter.get_wavelength()))
    print('range      = %d' % int(meter.sample()['range']))

def list(args):
    conn = openpd.Connection()
    print('Known OpenPD devices:')
    print()
    print('\n'.join(conn.list_devices()))
    sys.exit(0)

def main():
    parser = argparse.ArgumentParser(description='Periodically poll photodiode for power samples')
    parser.add_argument('-d', '--device', type=str, metavar='DEV_ID', help='Device to manipulate')
    parser.add_argument('-r', '--raw', action='store_true',
                        help='Connect directly to serial device (specify with --device)')
    subparsers = parser.add_subparsers()

    subp = subparsers.add_parser('list', help='List devices')
    subp.set_defaults(action=list)

    subp = subparsers.add_parser('config', help='View or change device configuration')
    subp.set_defaults(action=configure)
    subp.add_argument('-w', '--wavelength', type=int, help='Change wavelength')

    subp = subparsers.add_parser('acquire', help='Acquire data')
    subp.set_defaults(action=acquire)
    subp.add_argument('-t', '--timestamps', action='store_true', help='Emit timestamps with samples')
    subp.add_argument('-n', '--period', type=float, default=0.5, help='Sampling period in seconds')
    subp.add_argument('-o', '--output', type=argparse.FileType('w'), default=sys.stdout,
                      help='Output file')

    subp = subparsers.add_parser('help', help='Show help message')
    subp.set_defaults(action=lambda args: parser.print_help())

    args = parser.parse_args()
    try:
        args.action(args)
    except AttributeError:
        parser.print_help()

if __name__ == '__main__':
    main()

